print("Ввод суммы первоначального депозита")
a = float(input())
print("Первый год =", format(round(a*1.04, 2),'.2f'))
print("Второй год =", format(round(a*1.04*1.04, 2),'.2f'))
print("Третий год =", format(round(a*1.04*1.04*1.04, 2),'.2f'))